# #ddev-generated
# <my-project>/.ddev/php/shopware.ini
[PHP]
opcache.enable_file_override = 1
opcache.interned_strings_buffer = 20
# note contrary to Shopware's recommendations, do not disable validate_timestamps in dev environments
# opcache.validate_timestamps = 0
zend.assertions = -1
zend.detect_unicode = 0
realpath_cache_ttl = 3600
